import { useRef, useState } from "react";
import { Plus, Pencil, Trash2, ArrowRightLeft } from "lucide-react";
import { toast } from "sonner";
import api from "@/lib/api";
import { useStore } from "@/contexts/StoreContext";
import { useCompanyResource } from "@/hooks/useCompanyResource";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { PersonDialog } from "@/components/company/PersonDialog";
import { DebtPaymentEditDialog } from "@/components/company/DebtPaymentEditDialog";
import { BulkEditDialog } from "@/components/BulkEditDialog";
import { DebtPaymentDialog } from "@/components/company/DebtPaymentDialog";
import { DebtEditDialog } from "@/components/company/DebtEditDialog";
import { TextField, SelectField, CurrencyField, FormError, today, companyMoney, apiError } from "@/components/company/Fields";

export default function Debts() {
  const { stores } = useStore();
  const people = useCompanyResource("/company/people");
  const debts = useCompanyResource("/company/debts");
  const [form, setForm] = useState({ person_id: "", store_id: "ALL", direction: "payable", currency: "USD", amount: "", date: today(), due_date: "", cash_effect: false, note: "" });
  const [currencyFilter, setCurrencyFilter] = useState("ALL"), [statusFilter, setStatusFilter] = useState("open");
  const [search, setSearch] = useState("");
  const [personOpen, setPersonOpen] = useState(false), [payment, setPayment] = useState(null), [editingDebt, setEditingDebt] = useState(null), [editingPayment, setEditingPayment] = useState(null), [bulkEditing, setBulkEditing] = useState(false);
  const [selectedIds, setSelectedIds] = useState(() => new Set());
  const [busy, setBusy] = useState(false), [error, setError] = useState("");
  const requestId = useRef(crypto.randomUUID());
  const change = (key, value) => { setForm(f => ({ ...f, [key]: value })); requestId.current = crypto.randomUUID(); };
  const submit = async e => { e.preventDefault(); setBusy(true); setError(""); try { await api.post("/company/debts", { ...form, store_id: form.store_id === "ALL" ? null : form.store_id, due_date: form.due_date || null, amount: Number(form.amount), request_id: requestId.current }); toast.success("Borç/alacak kaydedildi"); debts.refresh(); change("amount", ""); } catch (e) { setError(apiError(e)); } finally { setBusy(false); } };
  const toggleSelected = id => setSelectedIds(current => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; });
  const removeDebts = async ids => { if (!window.confirm(`${ids.length} borç/alacak kaydı kalıcı olarak silinsin mi?`)) return; try { if (ids.length === 1) await api.delete(`/company/debts/${ids[0]}`); else await api.post("/company/debts/bulk-delete", { ids }); setSelectedIds(new Set()); toast.success(`${ids.length} borç/alacak kaydı silindi`); debts.refresh(); } catch (e) { toast.error(apiError(e)); } };
  const removePayment = async (debt, paymentId) => { if (!window.confirm("Bu ödeme/tahsilat silinsin mi?")) return; try { await api.delete(`/company/debts/${debt.id}/payments/${paymentId}`); toast.success("Ödeme/tahsilat silindi"); debts.refresh(); } catch (e) { toast.error(apiError(e)); } };
  const rows = (debts.data || []).filter(d => (currencyFilter === "ALL" || d.currency === currencyFilter) && (statusFilter === "ALL" || (statusFilter === "open" ? d.status !== "closed" : d.status === statusFilter)) && `${d.person_name} ${d.note}`.toLocaleLowerCase("tr").includes(search.toLocaleLowerCase("tr")));
  return <div className="space-y-7" data-testid="debts-page">
    <div className="flex justify-between items-center gap-3"><h2 className="text-lg font-display font-bold">Şirketin Borç & Alacakları</h2><Button onClick={() => setPersonOpen(true)} data-testid="debt-add-person"><Plus className="w-4 h-4 mr-2" />Kişi Ekle</Button></div>
    <FormError error={debts.error || people.error} id="debt-load-error" />
    <form onSubmit={submit} className="border-y border-slate-200 bg-white p-4 sm:p-6 space-y-5" data-testid="debt-form"><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
      <SelectField label="Kişi" id="debt-person" value={form.person_id} onChange={v => change("person_id", v)} options={(people.data || []).map(p => ({ value: p.id, label: p.name }))} />
      <SelectField label="Kayıt Türü" id="debt-direction" value={form.direction} onChange={v => change("direction", v)} options={[{ value: "payable", label: "Şirketin Borcu" }, { value: "receivable", label: "Şirketin Alacağı" }]} />
      <CurrencyField id="debt-currency" value={form.currency} onChange={v => change("currency", v)} />
      <TextField label="Tutar" id="debt-amount" value={form.amount} onChange={v => change("amount", v)} type="number" min="0.01" step="0.01" required />
      <TextField label="İşlem Tarihi" id="debt-date" value={form.date} onChange={v => change("date", v)} type="date" required />
      <TextField label="Vade (isteğe bağlı)" id="debt-due-date" value={form.due_date} onChange={v => change("due_date", v)} type="date" />
      <SelectField label="İlgili Mağaza" id="debt-store" value={form.store_id} onChange={v => change("store_id", v)} options={[{ value: "ALL", label: "Şirket Geneli" }, ...stores.map(s => ({ value: s.id, label: s.name }))]} />
      <div className="sm:col-span-2"><TextField label="Not" id="debt-note" value={form.note} onChange={v => change("note", v)} maxLength={500} /></div>
    </div><label className="flex items-start gap-3 text-sm" htmlFor="debt-cash-effect"><Checkbox id="debt-cash-effect" data-testid="debt-cash-effect" checked={form.cash_effect} onCheckedChange={v => change("cash_effect", v === true)} /><span>{form.direction === "payable" ? "Bu tutar fiilen şirket kasasına alındı" : "Bu tutar fiilen şirket kasasından ödendi"}</span></label><FormError error={error} id="debt-form-error" /><div className="flex justify-end"><Button type="submit" disabled={busy || !form.person_id} data-testid="debt-submit">{busy ? "Kaydediliyor…" : "Kaydı Ekle"}</Button></div></form>
    <div className="grid grid-cols-1 sm:grid-cols-3 gap-4"><TextField label="Kişi / Not Ara" id="debt-search" value={search} onChange={setSearch} /><SelectField label="Para Birimi" id="debt-currency-filter" value={currencyFilter} onChange={setCurrencyFilter} options={[{ value: "ALL", label: "TL ve USD" }, { value: "USD", label: "USD" }, { value: "TRY", label: "TL" }]} /><SelectField label="Durum" id="debt-status-filter" value={statusFilter} onChange={setStatusFilter} options={[{ value: "ALL", label: "Tümü" }, { value: "open", label: "Açık Kayıtlar" }, { value: "overdue", label: "Vadesi Geçen" }, { value: "closed", label: "Kapanan" }]} /></div>
    <div className="space-y-4"><div className="flex justify-end">{selectedIds.size > 0 && <div className="flex gap-2"><Button variant="outline" size="sm" onClick={() => setBulkEditing(true)}>Toplu Düzenle</Button><Button variant="destructive" size="sm" onClick={() => removeDebts([...selectedIds])}>Seçilenleri Sil ({selectedIds.size})</Button></div>}</div>{debts.loading ? <p data-testid="debt-loading">Yükleniyor…</p> : !rows.length ? <p data-testid="debts-empty" className="text-sm text-slate-500">Bu görünümde kayıt yok.</p> : rows.map(d => <article key={d.id} className="bg-white border border-slate-200 rounded-lg p-5 space-y-4" data-testid={`debt-row-${d.id}`}>
      <div className="flex flex-wrap justify-between gap-4"><div className="flex items-start gap-3"><Checkbox checked={selectedIds.has(d.id)} onCheckedChange={() => toggleSelected(d.id)} aria-label="Borç/alacak kaydını seç" /><div><strong>{d.person_name}</strong><p className="text-xs text-slate-500 mt-1">{d.direction === "payable" ? "Şirketin borcu" : "Şirketin alacağı"} · {d.store_name || "Şirket geneli"} · {d.date}</p><p className="text-xs text-slate-500 mt-1 break-words">{d.note}</p></div></div><div className="text-right"><p className="text-xs text-slate-500">Kalan</p><strong className={`text-xl font-mono-num ${d.direction === "payable" ? "text-rose-600" : "text-emerald-700"}`} data-testid={`debt-remaining-${d.id}`}>{companyMoney(d.remaining, d.currency)}</strong><p className="text-xs text-slate-500 mt-1">İlk tutar: {companyMoney(d.principal, d.currency)}</p><div className="flex justify-end gap-1 mt-2"><Button variant="ghost" size="icon" onClick={() => setEditingDebt(d)} aria-label="Borç/alacak kaydını düzenle" data-testid={`edit-debt-${d.id}`}><Pencil className="w-4 h-4" /></Button><Button variant="ghost" size="icon" onClick={() => removeDebts([d.id])} aria-label="Borç/alacak kaydını sil" data-testid={`delete-debt-${d.id}`} className="text-slate-400 hover:text-rose-600"><Trash2 className="w-4 h-4" /></Button></div></div></div>
      <div className="flex flex-wrap justify-between items-center gap-3"><span className={`text-xs ${d.status === "overdue" ? "text-rose-700" : "text-slate-500"}`} data-testid={`debt-status-${d.id}`}>{d.status === "closed" ? "Kapandı" : d.status === "overdue" ? "Vadesi geçti" : "Açık"}{d.due_date && ` · Vade: ${d.due_date}`}</span>{d.remaining > 0 && <Button variant="outline" onClick={() => setPayment(d)} data-testid={`pay-debt-${d.id}`}><ArrowRightLeft className="w-4 h-4 mr-2" />{d.direction === "payable" ? "Ödeme Kaydet" : "Tahsilat Kaydet"}</Button>}</div>
      {d.payments.length > 0 && <div className="border-t border-slate-100 pt-3 space-y-2">{d.payments.map(p => <div key={p.id} className="text-xs flex flex-wrap justify-between gap-2 text-slate-500" data-testid={`debt-payment-${p.id}`}><span>{p.date} · {p.note || "Ödeme / tahsilat"}</span><div className="flex items-center gap-2"><strong>{companyMoney(p.amount, d.currency)}</strong><Button variant="ghost" size="icon" onClick={() => setEditingPayment({ debt: d, payment: p })} aria-label="Ödeme/tahsilatı düzenle" data-testid={`edit-debt-payment-${p.id}`}><Pencil className="w-3 h-3" /></Button><Button variant="ghost" size="icon" onClick={() => removePayment(d, p.id)} aria-label="Ödeme/tahsilatı sil" data-testid={`delete-debt-payment-${p.id}`} className="text-slate-400 hover:text-rose-600"><Trash2 className="w-3 h-3" /></Button></div></div>)}</div>}
    </article>)}</div>
    {editingPayment && <DebtPaymentEditDialog debt={editingPayment.debt} payment={editingPayment.payment} onClose={() => setEditingPayment(null)} onSaved={debts.refresh} />}
    {bulkEditing && <BulkEditDialog title="Borç / Alacak Kayıtlarını Toplu Düzenle" description="Ödenmiş tutarlar ve bakiye kuralları korunur" endpoint="/company/debts/bulk-update" ids={[...selectedIds]} fields={[{ key: "amount", label: "Tutar", type: "number" }, { key: "date", label: "İşlem Tarihi", type: "date" }, { key: "due_date", label: "Vade", type: "date" }, { key: "person_id", label: "Kişi", type: "select", options: (people.data || []).map(person => ({ value: person.id, label: person.name })) }, { key: "store_id", label: "Mağaza", type: "select", options: stores.map(store => ({ value: store.id, label: store.name })) }, { key: "direction", label: "Kayıt Türü", type: "select", options: [{ value: "payable", label: "Şirketin Borcu" }, { value: "receivable", label: "Şirketin Alacağı" }] }, { key: "currency", label: "Para Birimi", type: "select", options: [{ value: "USD", label: "USD" }, { value: "TRY", label: "TL" }] }, { key: "cash_effect", label: "Kasa etkisi", type: "checkbox", checkboxLabel: "Kasa etkisini uygula" }, { key: "note", label: "Not" }]} onClose={() => setBulkEditing(false)} onSaved={() => { setBulkEditing(false); setSelectedIds(new Set()); debts.refresh(); }} />}
    {editingDebt && <DebtEditDialog debt={editingDebt} people={people.data || []} onClose={() => setEditingDebt(null)} onSaved={debts.refresh} />}
    {personOpen && <PersonDialog onClose={() => setPersonOpen(false)} onSaved={p => { people.refresh(); change("person_id", p.id); }} />}
    {payment && <DebtPaymentDialog debt={payment} onClose={() => setPayment(null)} onSaved={debts.refresh} />}
  </div>;
}