import { useRef, useState } from "react";
import { toast } from "sonner";
import api from "@/lib/api";
import { useCompanyResource } from "@/hooks/useCompanyResource";
import { Button } from "@/components/ui/button";
import { CurrencyField, TextField, SelectField, FormError, today, companyMoney, currencyName, apiError } from "@/components/company/Fields";

const labels = { capital_contribution: "Sermaye Girişi", capital_withdrawal: "Sermaye İadesi", debt_payable: "Borç Alındı", debt_receivable: "Borç Verildi", repayment: "Borç Ödemesi", collection: "Alacak Tahsilatı", cash_in: "Nakit Girişi", cash_out: "Nakit Çıkışı" };
export default function CompanyOverview() {
  const resource = useCompanyResource("/company/overview");
  const [form, setForm] = useState({ currency: "USD", direction: "in", amount: "", date: today(), note: "" });
  const [busy, setBusy] = useState(false), [error, setError] = useState("");
  const [currency, setCurrency] = useState("ALL"), [start, setStart] = useState(""), [end, setEnd] = useState("");
  const requestId = useRef(crypto.randomUUID());
  const change = (k, v) => { setForm(f => ({ ...f, [k]: v })); requestId.current = crypto.randomUUID(); };
  const save = async e => { e.preventDefault(); setBusy(true); setError(""); try { await api.post("/company/cash", { ...form, amount: Number(form.amount), request_id: requestId.current }); toast.success("Kasa hareketi kaydedildi"); change("amount", ""); resource.refresh(); } catch (e) { setError(apiError(e)); } finally { setBusy(false); } };
  const data = resource.data;
  const invalidDates = start && end && start > end;
  const rows = invalidDates ? [] : (data?.ledger || []).filter(r => (currency === "ALL" || r.currency === currency) && (!start || r.date >= start) && (!end || r.date <= end));
  return <div className="space-y-7" data-testid="company-overview-page">
    <FormError error={resource.error} id="company-overview-error" />
    <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">{(data?.balances || [{ currency: "USD" }, { currency: "TRY" }]).map(b => <section key={b.currency} className="border-y border-slate-200 py-5" data-testid={`company-balance-${b.currency.toLowerCase()}`}><p className="text-sm text-slate-500">{currencyName(b.currency)} Nakit Kasası</p><strong className="font-mono-num text-3xl break-all block mt-2" data-testid={`company-cash-${b.currency.toLowerCase()}`}>{companyMoney(b.cash_balance, b.currency)}</strong><div className="grid grid-cols-2 gap-4 mt-5 text-sm"><div><p className="text-xs text-slate-500">Alacaklar</p><strong className="text-emerald-700" data-testid={`company-receivables-${b.currency.toLowerCase()}`}>{companyMoney(b.receivables, b.currency)}</strong></div><div><p className="text-xs text-slate-500">Borçlar</p><strong className="text-rose-600" data-testid={`company-payables-${b.currency.toLowerCase()}`}>{companyMoney(b.payables, b.currency)}</strong></div></div>{b.cash_balance < 0 && <p className="text-xs text-amber-800 mt-3" data-testid={`company-negative-cash-${b.currency.toLowerCase()}`}>Kayıtlı nakit eksi; açılış bakiyesi veya eksik nakit girişleri olabilir.</p>}</section>)}</div>
    <section className="bg-emerald-50 border-y border-emerald-200 p-5 space-y-3"><div className="flex flex-wrap justify-between gap-4"><div><h2 className="text-base font-semibold">Aktarılan Mağaza Kâr / Zararı</h2><p className="text-xs text-emerald-800 mt-1">Kapanmış ayların nakit dışı muhasebe kaydı · USD</p></div><strong className="text-2xl font-mono-num" data-testid="company-closed-profit">{companyMoney(data?.closed_profit_usd)}</strong></div><div className="flex justify-between flex-wrap gap-3 border-t border-emerald-200 pt-3 text-sm"><span>USD muhasebe bakiyesi <span className="text-xs text-emerald-800">(USD nakit + kapanışlar; TL ayrı)</span></span><strong data-testid="company-book-balance">{companyMoney(data?.book_balance_usd)}</strong></div>{data?.blocked_closings > 0 && <p role="alert" className="text-sm text-rose-700" data-testid="company-blocked-close">{data.blocked_closings} kapanış kur verisi bekliyor; muhasebe toplamı gösterilmiyor.</p>}</section>
    <form onSubmit={save} className="border-y border-slate-200 bg-white p-4 sm:p-6 space-y-4" data-testid="company-cash-form"><h2 className="font-display font-bold text-lg">Nakit / Açılış Hareketi</h2><div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4"><CurrencyField id="cash-currency" value={form.currency} onChange={v => change("currency", v)} /><SelectField id="cash-direction" label="Hareket" value={form.direction} onChange={v => change("direction", v)} options={[{ value: "in", label: "Nakit Girişi" }, { value: "out", label: "Nakit Çıkışı" }]} /><TextField id="cash-amount" label="Tutar" value={form.amount} onChange={v => change("amount", v)} type="number" min="0.01" step="0.01" required /><TextField id="cash-date" label="Tarih" value={form.date} onChange={v => change("date", v)} type="date" required /></div><TextField id="cash-note" label="Açıklama" value={form.note} onChange={v => change("note", v)} maxLength={500} /><FormError error={error} id="cash-form-error" /><div className="flex justify-end"><Button type="submit" disabled={busy} data-testid="cash-submit">{busy ? "Kaydediliyor…" : "Hareketi Kaydet"}</Button></div></form>
    <section className="space-y-4"><h2 className="font-display font-bold text-lg">Gerçek Nakit Hareketleri</h2><div className="grid grid-cols-1 sm:grid-cols-3 gap-4"><SelectField label="Para Birimi" id="cash-filter-currency" value={currency} onChange={setCurrency} options={[{ value: "ALL", label: "TL ve USD" }, { value: "USD", label: "USD" }, { value: "TRY", label: "TL" }]} /><TextField label="Başlangıç" id="cash-filter-start" value={start} onChange={setStart} type="date" /><TextField label="Bitiş" id="cash-filter-end" value={end} onChange={setEnd} type="date" /></div><FormError error={invalidDates ? "Geçerli tarih aralığı seçin." : ""} id="cash-filter-error" />
      {!resource.loading && !rows.length && <p className="text-sm text-slate-500" data-testid="cash-empty">Bu aralıkta nakit hareketi yok.</p>}
      {rows.map(r => <div key={`${r.kind}-${r.id}`} className="border-b border-slate-200 py-3 flex flex-wrap justify-between gap-3" data-testid={`cash-row-${r.kind}-${r.id}`}><div><strong className="text-sm">{labels[r.kind] || r.kind} {r.person_name && `· ${r.person_name}`}</strong><p className="text-xs text-slate-500 mt-1">{r.date} {r.store_name && `· ${r.store_name}`}</p><p className="text-xs text-slate-500 break-words mt-1">{r.note}</p></div><strong className={`font-mono-num ${r.amount < 0 ? "text-rose-600" : "text-emerald-700"}`}>{companyMoney(r.amount, r.currency)}</strong></div>)}
    </section>
  </div>;
}