import { useState } from "react";
import { toast } from "sonner";
import api from "@/lib/api";
import { useStore } from "@/contexts/StoreContext";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { TextField, SelectField, CurrencyField, FormError, apiError } from "@/components/company/Fields";

export const DebtEditDialog = ({ debt, people, onClose, onSaved }) => {
  const { stores } = useStore();
  const [form, setForm] = useState({ amount: debt.principal, date: debt.date, note: debt.note || "", person_id: debt.person_id, store_id: debt.store_id || "ALL", direction: debt.direction, currency: debt.currency, due_date: debt.due_date || "", cash_effect: debt.cash_effect });
  const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const change = (key, value) => setForm(current => ({ ...current, [key]: value }));
  const save = async event => { event.preventDefault(); setBusy(true); setError(""); try { await api.put(`/company/debts/${debt.id}`, { ...form, amount: Number(form.amount), store_id: form.store_id === "ALL" ? null : form.store_id, due_date: form.due_date || null }); toast.success("Borç/alacak güncellendi"); onSaved(); onClose(); } catch (err) { setError(apiError(err)); } finally { setBusy(false); } };
  return <Dialog open onOpenChange={open => { if (!open && !busy) onClose(); }}><DialogContent className="bg-white max-w-2xl" data-testid="debt-edit-dialog"><DialogHeader><DialogTitle>Borç / Alacak Kaydını Düzenle</DialogTitle><DialogDescription>{debt.person_name} · {debt.date}</DialogDescription></DialogHeader><form onSubmit={save} className="space-y-4"><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><SelectField label="Kişi" id="edit-debt-person" value={form.person_id} onChange={v => change("person_id", v)} options={people.map(person => ({ value: person.id, label: person.name }))} /><SelectField label="Kayıt Türü" id="edit-debt-direction" value={form.direction} onChange={v => change("direction", v)} options={[{ value: "payable", label: "Şirketin Borcu" }, { value: "receivable", label: "Şirketin Alacağı" }]} /><CurrencyField id="edit-debt-currency" value={form.currency} onChange={v => change("currency", v)} /><TextField label="Tutar" id="edit-debt-amount" value={form.amount} onChange={v => change("amount", v)} type="number" min="0.01" step="0.01" required /><TextField label="İşlem Tarihi" id="edit-debt-date" value={form.date} onChange={v => change("date", v)} type="date" required /><TextField label="Vade" id="edit-debt-due" value={form.due_date} onChange={v => change("due_date", v)} type="date" /><SelectField label="İlgili Mağaza" id="edit-debt-store" value={form.store_id} onChange={v => change("store_id", v)} options={[{ value: "ALL", label: "Şirket Geneli" }, ...stores.map(store => ({ value: store.id, label: store.name }))]} /><TextField label="Not" id="edit-debt-note" value={form.note} onChange={v => change("note", v)} maxLength={500} /></div><FormError error={error} id="edit-debt-error" /><DialogFooter><Button type="button" variant="outline" disabled={busy} onClick={onClose}>Vazgeç</Button><Button type="submit" disabled={busy}>{busy ? "Kaydediliyor…" : "Güncelle"}</Button></DialogFooter></form></DialogContent></Dialog>;
};
